// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ondbephqkaixpfujqjlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZGJlcGhxa2FpeHBmdWpxamxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODk0NDIsImV4cCI6MjA2Mjc2NTQ0Mn0.4pH9psVF4Ks2HMOhpgdI2QDbftu8v1Qm7OYYDQn2oEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);